import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "src/styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>LaDMasC House</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
